---
- hosts: localhost
  roles:
    - role: tower_connect
      gather_facts: no
      vars:
        controller_oauthtoken: "{{oauth_token}}"

- name: Add user to Controller
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_validate_certs: false
    controller_hostname: "{{tower_host}}"
    controller_oauthtoken: "{{oauth_token}}"
    controller_username: "{{ ldap_user }}"
    controller_password: "{{ ldap_pwd }}"

  collections:
    - redhat_cop.controller_configuration

  pre_tasks:
    - name: Include vars from controller_configs directory
      include_vars:
        dir: ./configs
        extensions: ["yml"]

  roles:
    #- {role: redhat_cop.controller_configuration.organizations, when: controller_organizations is defined}
    #- {role: redhat_cop.controller_configuration.users, when: controller_user_accounts is defined}
    #- {role: redhat_cop.controller_configuration.teams, when: controller_teams is defined}
    #- {role: redhat_cop.controller_configuration.roles, when: controller_roles is defined}
    #- {role: redhat_cop.controller_configuration.credentials, when: controller_credentials is defined}
    #- {role: redhat_cop.controller_configuration.inventories, when: controller_inventories is defined}
    - role: inventory_scripts
#    - {role: redhat_cop.controller_configuration.inventory_sources, when: controller_inventory_sources is defined}
    #- {role: redhat_cop.controller_configuration.projects, when: controller_projects is defined}
    #- {role: redhat_cop.controller_configuration.job_templates, when: controller_templates is defined}
#    - {role: redhat_cop.controller_configuration.workflow_job_templates, when: controller_workflows is defined}
